local islandsList = {
    "???? Shrine",
    "A rock",
    "Coco Island",
    "Colosseum",
    "Fishman Cave",
    "Fishman Island",
    "Gravito's Fort",
    "Island Of Zou",
    "Kori Island",
    "Land of the Sky",
    "Logue Town",
    "Marine Base G-1",
    "Marine Fort F-1",
    "Mysterious Cliff",
    "Orange Town",
    "Restaurant Baratie",
    "Reverse Mountain",
    "Roca Island",
    "Sandora",
    "Shark Park",
    "Shell's Town",
    "Sphinx Island",
    "Town of Beginnings"
}
